### ISSUE TITLE
Add name validation for C# code

### ISSUE THREAD

**Issue by dmodena** [dmodena/polyglot-registration#4]
The C# console app needs to validate the input name. Please follow validation rules from [documentation](https://github.com/dmodena/polyglot-registration/blob/main/src/README.md).

**Comment by SamudraThio** [comment]
Hi, I'd love to try this one. Would you be able to assign it to me? I'll submit my pull request soon. Reading the other pull requests looks like I won't be able to do multiple, but if you have unfinished C# items, let me know!

**Comment by dmodena** [comment]
Thank you! Go ahead, and submit your Pull Request! Only for this month, I will be taking one PR by contributor, but you are free to submit more after that!

**Comment by SamudraThio** [comment]
This was my first pull request ever and it was a really fun project! It was also really cool to see all the tests work as well. Please let me know if you see any room for improvement. I saw that the checks failed, but I think the tests run all 3 validations (name/document/email) instead of just the name validation tests. Thank you for the opportunity.

**Comment by dmodena** [comment]
Completed with PR #19
